In [1]:
import pandas as pd
!pip install transformers

     |████████████████████████████████| 4.2 MB 16.1 MB/s 
     |████████████████████████████████| 6.6 MB 66.9 MB/s 
     |████████████████████████████████| 84 kB 2.2 MB/s 
     |████████████████████████████████| 596 kB 52.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
# Code to read csv file into Colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [3]:
link = 'https://drive.google.com/file/d/1a1mZHqe3o1psMlsaXrqIUOe9IiYQ2gRT/view?usp=sharing' 

In [4]:
# to get the id part of the file
id = link.split("/")[-2]
 
downloaded = drive.CreateFile({'id':id})
downloaded.GetContentFile('Survey_Results_Labeled_Dec.csv') 
 
df = pd.read_csv('Survey_Results_Labeled_Dec.csv')
df

Unnamed: 0                                               text    1    2  \
0           Q1  "Tucker Carlson seem to have forgotten that Ru...  0.1  0.0   
1           Q2  "Analysis: Would Putin get away with invading ...  0.0  0.4   
2           Q3  "Kiev, Ukraine - Ukrainian defense officials s...  0.0  0.8   
3           Q4  Russia-Ukraine tensions: why Russia is putting...  0.0  0.5   
4           Q5  @ManMadeMoon I don’t think it’s that deep. I t...  0.1  0.0   
..         ...                                                ...  ...  ...   
97         Q96  "@peterpomeranzev Putin doesn't want to invade...  0.0  0.2   
98         Q97  @JonScottFNC Ukrainians remember The Holodomor...  0.0  0.2   
99         Q98  ‘Fake news’ may complicate Putin-Biden talks –...  0.0  0.9   
100        Q99  "Russia kept EU busy by instigating a hybrid w...  0.0  0.5   
101       Q100  Timcast IRL - Biden Threatens US Deployment If...  0.1  0.6   

       3     Label  
0    0.9  negative  
1    0.6  negative  
2    0.2   neutral  
3    0.5   neutral  
4    0.9  negative  
..   ...       ...  
97   0.8  negative  
98   0.8  negative  
99   0.1   neutral  
100  0.5   neutral  
101  0.3   neutral  

[102 rows x 6 columns]

In [5]:
df['Sentiment'] = 0

In [6]:
df

Unnamed: 0                                               text    1    2  \
0           Q1  "Tucker Carlson seem to have forgotten that Ru...  0.1  0.0   
1           Q2  "Analysis: Would Putin get away with invading ...  0.0  0.4   
2           Q3  "Kiev, Ukraine - Ukrainian defense officials s...  0.0  0.8   
3           Q4  Russia-Ukraine tensions: why Russia is putting...  0.0  0.5   
4           Q5  @ManMadeMoon I don’t think it’s that deep. I t...  0.1  0.0   
..         ...                                                ...  ...  ...   
97         Q96  "@peterpomeranzev Putin doesn't want to invade...  0.0  0.2   
98         Q97  @JonScottFNC Ukrainians remember The Holodomor...  0.0  0.2   
99         Q98  ‘Fake news’ may complicate Putin-Biden talks –...  0.0  0.9   
100        Q99  "Russia kept EU busy by instigating a hybrid w...  0.0  0.5   
101       Q100  Timcast IRL - Biden Threatens US Deployment If...  0.1  0.6   

       3     Label  Sentiment  
0    0.9  negative          0  
1    0.6  negative          0  
2    0.2   neutral          0  
3    0.5   neutral          0  
4    0.9  negative          0  
..   ...       ...        ...  
97   0.8  negative          0  
98   0.8  negative          0  
99   0.1   neutral          0  
100  0.5   neutral          0  
101  0.3   neutral          0  

[102 rows x 7 columns]

In [7]:
from google.colab import drive
drive.mount('drive')
import sys
sys.path.append('drive/My Drive/Colab Notebooks')

Mounted at drive


In [8]:
#code from NLPiation

import torch
from transformers import BertForSequenceClassification, Trainer, TrainingArguments, AutoTokenizer, EarlyStoppingCallback
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# Load the BERT Tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased')

# The dataset class
class TheDataset(torch.utils.data.Dataset):

    def __init__(self, reviews, sentiments, tokenizer):
        self.reviews    = reviews
        self.sentiments = sentiments
        self.tokenizer  = tokenizer
        self.max_len    = tokenizer.model_max_length
  
    def __len__(self):
        return len(self.reviews)
  
    def __getitem__(self, index):
        review = str(self.reviews[index])
        sentiments = self.sentiments[index]

        encoded_review = self.tokenizer.encode_plus(
            review,
            add_special_tokens    = True,
            max_length            = 128,
            return_token_type_ids = False,
            return_attention_mask = True,
            return_tensors        = 'pt',
            padding               = "max_length",
            truncation            = True
        )

        return {
            'input_ids': encoded_review['input_ids'][0],
            'attention_mask': encoded_review['attention_mask'][0],
            'labels': torch.tensor(sentiments, dtype=torch.long)
        }

# Prepare the Train/Validation sets
#train_set_dataset = TheDataset(
    #reviews    = train_set.text.tolist(),
    #sentiments = train_set.Sentiment.tolist(),
    #tokenizer  = tokenizer,
#)

#valid_set_dataset = TheDataset(
    #reviews    = valid_set.text.tolist(),
    #sentiments = valid_set.Sentiment.tolist(),
    #tokenizer  = tokenizer,
#)

# Load the BERT model
#model = BertForSequenceClassification.from_pretrained("drive/My Drive/Colab Notebooks/epoch 4", problem_type="single_label_classification", num_labels=3)

# Freeze the whole BERT model and train just the classifier
#for name, param in model.bert.named_parameters():
    #param.requires_grad = False

# Freeze BERT except the pooler layer
#for name, param in model.bert.named_parameters():
    #if not name.startswith('pooler'):
        #param.requires_grad = False

# Freeze the first 18 layers of the BERT
#for name, param in model.bert.named_parameters():
    #if ( not name.startswith('pooler') ) and "layer.23" and "layer.22" and "layer.21" and "layer.20" and "layer.19" and "layer.18" not in name :
        #param.requires_grad = False

# The function to get the accuracy
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='macro')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

# Define the training parameters
training_args = TrainingArguments(
    output_dir                  = 'drive/My Drive/Colab Notebooks',
    num_train_epochs            = 2,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size  = 64,
    warmup_steps                = 10000,
    learning_rate               = 5e-5,
    weight_decay                = 0.01,
    adam_beta1                  = 0.9,
    adam_beta2                  = 0.999,
    save_strategy               = "epoch",
    evaluation_strategy         = "epoch",
    eval_steps                  = 1,
    #save_total_limit            = 5,
    #metric_for_best_model       = 'eval_loss',
    load_best_model_at_end      =True
)

# Define the Huggingface Trainer object
#trainer = Trainer(
    #model           = model,
    #args            = training_args,
    #train_dataset   = train_set_dataset,
    #eval_dataset    = valid_set_dataset,
    #compute_metrics = compute_metrics,
    #callbacks       = [EarlyStoppingCallback(early_stopping_patience=3)]
#)


Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

In [9]:
# Load the checkpoint
model = BertForSequenceClassification.from_pretrained("drive/My Drive/Colab Notebooks/Bert_large_Dec/checkpoint-11228", num_labels=3)

# Make the test set ready
test_set_dataset = TheDataset(
    reviews    = df.text.tolist(),
    sentiments = df.Sentiment.tolist(),
    tokenizer  = tokenizer,
)

training_args = TrainingArguments(
    output_dir = 'drive/My Drive/Colab Notebooks',
    do_predict = True
)

trainer = Trainer(
    model           = model,
    args            = training_args,
    compute_metrics =compute_metrics,
)

PredictionOutput = trainer.predict(test_set_dataset)

***** Running Prediction *****
  Num examples = 102
  Batch size = 8


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
import numpy as np
PredictionOutput

PredictionOutput(predictions=array([[ 0.700961  ,  0.05845553, -0.3829156 ],
       [-2.2989237 ,  4.1592317 , -0.53028965],
       [-1.7864285 , -1.9573379 ,  3.0018635 ],
       [ 3.6113431 , -1.2394594 , -2.2496781 ],
       [ 2.9247446 , -1.6323777 , -1.235769  ],
       [-0.40694064,  3.0574942 , -1.8650384 ],
       [ 4.489735  , -2.0025496 , -2.337985  ],
       [-1.7616857 , -1.6845269 ,  2.8504014 ],
       [ 3.9400842 , -2.0266    , -1.8751236 ],
       [-0.5598135 ,  2.1945264 , -0.8029382 ],
       [-1.0204382 ,  1.3494457 ,  0.44036785],
       [ 4.119141  , -2.3270655 , -1.9738004 ],
       [ 1.7965063 , -0.63485473, -0.8967926 ],
       [ 2.3429601 , -2.4363818 , -0.38868734],
       [ 3.959503  , -1.9393789 , -2.0445514 ],
       [-0.8795827 , -1.2162933 ,  1.841067  ],
       [ 0.6380388 , -1.7925891 ,  0.9065763 ],
       [ 0.1850707 ,  0.3729314 , -0.2638369 ],
       [ 0.2812664 , -0.69719195,  0.35124952],
       [-0.75298053,  1.5120878 , -0.08227672],
       [ 3.

In [11]:
PredictionOutput[0]

array([[ 0.700961  ,  0.05845553, -0.3829156 ],
       [-2.2989237 ,  4.1592317 , -0.53028965],
       [-1.7864285 , -1.9573379 ,  3.0018635 ],
       [ 3.6113431 , -1.2394594 , -2.2496781 ],
       [ 2.9247446 , -1.6323777 , -1.235769  ],
       [-0.40694064,  3.0574942 , -1.8650384 ],
       [ 4.489735  , -2.0025496 , -2.337985  ],
       [-1.7616857 , -1.6845269 ,  2.8504014 ],
       [ 3.9400842 , -2.0266    , -1.8751236 ],
       [-0.5598135 ,  2.1945264 , -0.8029382 ],
       [-1.0204382 ,  1.3494457 ,  0.44036785],
       [ 4.119141  , -2.3270655 , -1.9738004 ],
       [ 1.7965063 , -0.63485473, -0.8967926 ],
       [ 2.3429601 , -2.4363818 , -0.38868734],
       [ 3.959503  , -1.9393789 , -2.0445514 ],
       [-0.8795827 , -1.2162933 ,  1.841067  ],
       [ 0.6380388 , -1.7925891 ,  0.9065763 ],
       [ 0.1850707 ,  0.3729314 , -0.2638369 ],
       [ 0.2812664 , -0.69719195,  0.35124952],
       [-0.75298053,  1.5120878 , -0.08227672],
       [ 3.771716  , -1.7148384 , -2.002

In [12]:
df['Bert_Large label'] = [np.argmax(i) for i in (PredictionOutput[0])]

In [13]:
df['Bert_Large label'].replace({0: "negative", 1: "neutral", 2: 'positive'}, inplace=True)

In [14]:
results = df['Bert_Large label'].value_counts()

In [15]:
results

negative    59
positive    23
neutral     20
Name: Bert_Large label, dtype: int64

In [16]:
df['Bert_Large label'].value_counts()

negative    59
positive    23
neutral     20
Name: Bert_Large label, dtype: int64

In [17]:
#delete control tweets from set
df = df.drop(33)
df = df.drop(67)

In [18]:
#change column names to make clear what is what
df = df.rename(columns={"Label":"Manual Label"})

In [19]:
#drop unnecessary column used as fake true label.
df = df.drop('Sentiment',axis=1)

In [26]:
print(df.to_markdown())

|     | Unnamed: 0   | text                                                                                                                                                                                                                                                                                                                         |   1 |   2 |   3 | Manual Label   | Bert_Large label   |
|----:|:-------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----:|----:|----:|:---------------|:-------------------|
|   0 | Q1           | "Tucker Carlson seem to have forgotten that Russia stole Crimea from Ukraine last night!                                                                                             

In [29]:
 import sklearn
 from sklearn.metrics import balanced_accuracy_score, precision_recall_fscore_support,classification_report
 b_a_Bert_Large = balanced_accuracy_score(df['Manual Label'], df['Bert_Large label'])
 p_r_f1_class_Bert_Large = precision_recall_fscore_support(df['Manual Label'], df['Bert_Large label'], average=None, labels=['negative', 'neutral', 'positive'])
 p_r_f1_Bert_Large = precision_recall_fscore_support(df['Manual Label'], df['Bert_Large label'], average='macro')

In [22]:
print(b_a_Bert_Large)
print(p_r_f1_Bert_Large)
print(p_r_f1_class_Bert_Large)

0.295014245014245
(0.39482758620689656, 0.295014245014245, 0.3212121212121212, None)
(array([0.53448276, 0.65      , 0.        ]), array([0.59615385, 0.28888889, 0.        ]), array([0.56363636, 0.4       , 0.        ]), array([52, 45,  3]))


In [31]:
 report = classification_report(df['Manual Label'], df['Bert_Large label'])

In [40]:
y_true.value_counts()

negative    52
neutral     45
positive     3
Name: Manual Label, dtype: int64

In [41]:
y_pred.value_counts()

negative    58
positive    22
neutral     20
Name: Bert_Large label, dtype: int64

In [42]:
p_r_f1_class_Bert_Large

(array([0.53448276, 0.65      , 0.        ]),
 array([0.59615385, 0.28888889, 0.        ]),
 array([0.56363636, 0.4       , 0.        ]),
 array([52, 45,  3]))

In [ ]:
import pandas as pd
y_actu = df['Manual Label']
y_pred = df['Bert_Large label']
df_confusion = pd.crosstab(y_actu, y_pred)

In [ ]:
df_confusion

Bert_Large label  negative  neutral  positive
Manual Label                                 
negative                31        7        14
neutral                 24       13         8
positive                 3        0         0

In [ ]:
#Get accuracies per class order (negative, neutral, positive)
from sklearn.metrics import confusion_matrix
y_true = df['Manual Label']
y_pred = df['Bert_Large label']
matrix = confusion_matrix(y_true, y_pred)
matrix.diagonal()/matrix.sum(axis=1)

array([0.59615385, 0.28888889, 0.        ])

In [ ]:
from google.colab import drive
drive.mount('drive')

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).


In [ ]:
df.to_csv('BERT_Large_Test_Dec.csv')
!cp BERT_Large_Test_Dec.csv "/content/drive/My Drive/Colab Notebooks"

